[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
thiserror = "1.0.51"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
